website_name            = "schwitzd.me"
github_repo_name        = "schwitzd.me"
resource_group_name     = "personal-site"
resource_group_location = "Switzerland North"
vault_address           = "http://127.0.0.1:8200"